add format

diff --git a/.github/workflows/metal-cpp-golang-rust.yml b/.github/workflows/metal-cpp-golang-rust.yml
--- a/.github/workflows/metal-cpp-golang-rust.yml
+++ b/.github/workflows/metal-cpp-golang-rust.yml
@@ -28,38 +28,37 @@ jobs:
     uses: ./.github/workflows/check-changed-files.yml
 
 
-#### Assume this runs in linux CI
-  # check-format:
-  #   name: Check Code Format
-  #   runs-on: ubuntu-22.04
-  #   needs: check-changed-files
-  #   container:
-  #     image: silkeh/clang:19-bookworm # Replace with a container having the desired clang-format version
-  #   steps:
-  #   - name: Checkout
-  #     uses: actions/checkout@v4
-  #   - name: Setup go
-  #     if: needs.check-changed-files.outputs.golang == 'true'
-  #     uses: actions/setup-go@v5
-  #     with:
-  #       go-version: '1.22.0'
-  #   - name: Check clang-format
-  #     if: needs.check-changed-files.outputs.cpp == 'true'
-  #     run: |
-  #       clang-format --version  
-  #       ./scripts/format_all.sh . --check --exclude "build|wrappers"
-  #   - name: Check gofmt
-  #     if: needs.check-changed-files.outputs.golang == 'true'
-  #     run: if [[ $(go list ./... | xargs go fmt) ]]; then echo "Please run go fmt"; exit 1; fi
-  #   - name: Check rustfmt
-  #     if: needs.check-changed-files.outputs.rust == 'true'
-  #     working-directory: ./wrappers/rust
-  #     # "-name target -prune" removes searching in any directory named "target"
-  #     # Formatting by single file is necessary due to generated files not being present
-  #     # before building the project.
-  #     # e.g. icicle-metal-runtime/src/bindings.rs is generated and icicle-metal-runtime/src/lib.rs includes that module
-  #     # causing rustfmt to fail.
-  #     run: if [[ $(find . -path ./icicle-curves/icicle-curve-template -prune -o -name target -prune -o -iname *.rs -print | xargs cargo fmt --check --) ]]; then echo "Please run cargo fmt"; exit 1; fi
+  check-format:
+    name: Check Code Format
+    runs-on: ubuntu-22.04
+    needs: check-changed-files
+    container:
+      image: silkeh/clang:19-bookworm # Replace with a container having the desired clang-format version
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v4
+    - name: Setup go
+      if: needs.check-changed-files.outputs.golang == 'true'
+      uses: actions/setup-go@v5
+      with:
+        go-version: '1.22.0'
+    - name: Check clang-format
+      if: needs.check-changed-files.outputs.cpp == 'true'
+      run: |
+        clang-format --version  
+        ./scripts/format_all.sh . --check --exclude "build|wrappers"
+    - name: Check gofmt
+      if: needs.check-changed-files.outputs.golang == 'true'
+      run: if [[ $(go list ./... | xargs go fmt) ]]; then echo "Please run go fmt"; exit 1; fi
+    - name: Check rustfmt
+      if: needs.check-changed-files.outputs.rust == 'true'
+      working-directory: ./wrappers/rust
+      # "-name target -prune" removes searching in any directory named "target"
+      # Formatting by single file is necessary due to generated files not being present
+      # before building the project.
+      # e.g. icicle-metal-runtime/src/bindings.rs is generated and icicle-metal-runtime/src/lib.rs includes that module
+      # causing rustfmt to fail.
+      run: if [[ $(find . -path ./icicle-curves/icicle-curve-template -prune -o -name target -prune -o -iname *.rs -print | xargs cargo fmt --check --) ]]; then echo "Please run cargo fmt"; exit 1; fi
 
   extract-metal-backend-branch:
     uses: ./.github/workflows/extract-backends.yml
